name: gabrielalves deployment

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: echo Building the app

  deploy-development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://gabrielalves.me
    needs: build
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > private_key
          chmod 600 private_key
          ssh-add private_key

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc --delete"
            SOURCE: "src/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: ${{ secrets.REMOTE_TARGET }}